#
# This is an example of using VeraDemo Java test application with the Veracode Static Pipeline scanner.  

# A Veracode subscription is required.
trigger:
- none

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: Build
    jobs:
    - job: doBuild
      steps:
      - task: Maven@3
        displayName: Build with Maven
        inputs:
          mavenPomFile: 'app/pom.xml'
          mavenOptions: '-Xmx3072m'
          javaHomeOption: 'JDKVersion'
          jdkVersionOption: '1.8'
          jdkArchitectureOption: 'x64'
          publishJUnitResults: false
          goals: 'package'

  - stage: PolicyScan
    jobs:
    - job: doStaticScan
      steps:
      - script: |
          echo buildNumber: $(build.buildNumber)
          echo binDir: $(build.binariesDirectory)
          echo artDir: $(build.artifactstagingdirectory)
          echo srcDir: $(build.sourcesDirectory)
        target: host
      - task: Veracode@3
        inputs:
          ConnectionDetailsSelection: 'Credentials'
          apiId: $(VERACODE_API_ID)
          apiKey: $(VERACODE_API_KEY)
          veracodeAppProfile: 'Verademo'
          version: 'Azure-$(build.buildNumber)'
          filepath: '$(build.artifactstagingdirectory)/target/verademo.war'

