version: 0.2

phases:
  build:
    commands:
       - java -jar /opt/veracode/api-wrapper.jar -action uploadandscan -vid $API_ID -vkey $API_KEY -appname Verademo -createprofile false -version AWS-$(date +%Y-%m-%d-%H:%M) -filepath verademo.war
