version: 0.2

env:
  secrets-manager:
    DOCKERHUB_USERNAME: "/dockerhub/credentials:username"
    DOCKERHUB_PASSWORD: "/dockerhub/credentials:password"
phases:
  pre_build:
    commands:
      - echo logging into DockerHub
      - docker login --username $DOCKERHUB_USERNAME --password $DOCKERHUB_PASSWORD
  build:
    commands:
       - java -jar /opt/veracode/api-wrapper.jar -action uploadandscan -vid $VERACODE_API_ID -vkey $VERACODE_API_KEY -appname Verademo -createprofile false -version AWS-$(date +%Y-%m-%d-%H:%M) -filepath verademo.war
