name: 4-Deploy-QA-DAST-Scan

on:
  workflow_dispatch:
  schedule:
  - cron: "0 22 * * 1,3,5"

# Run the Docker image for QA and DAST testing
jobs:
  Checkout-Build-Artifact:
    runs-on: [self-hosted]
    steps:     
      - name: Pull Docker
        run: |
         docker pull veracodedemolabs/verademo-java-github:latest
