name: 1-Checkout-Build-Artifact

on:
  workflow_dispatch:
  schedule:
  - cron: "0 22 * * 1,3,5"

# Run the Docker image for QA and DAST testing
jobs:
  Checkout-Build-Artifact:
    runs-on: [ubuntu-github-docker]
    steps:     
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.0
        with:
        # Artifact name
          name: verademo.war
          path: app/target/verademo.war
      
      - name: Pull Docker
        run: |
         docker pull veracodedemolabs/verademo-java-github:latest
