name: 4-Deploy-QA-DAST-Scan

# Only triggers manually or when the build "3-Build and Publish Docker Image" workflow succeeds

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["3-Build and Publish Docker Image"]
    types:
      - completed
      
# Run the Docker image for QA and DAST testing
jobs:
  Deploy-Docker-Image-QA-Server:
    runs-on: [self-hosted]
    steps:     
      - name: Pull Docker
        run: |
         docker pull veracodedemolabs/verademo-java-github:latest

      - name: Pull Docker
        run: |
         docker run -p 8080:8080 veracodedemolabs/verademo-java-github:latest
       
