name: 4-Deploy-QA-DAST-Scan

# Only triggers manually or when the build "3-Build and Publish Docker Image" workflow succeeds

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["3-Build and Publish Docker Image"]
    types:
      - completed
      
# Run the Docker image for QA and DAST testing
jobs:
  Deploy-Docker-Image-QA-Server:
    runs-on: [self-hosted]
    steps:     
      - name: Pull Docker Image to QA Web Server
        run: |
         docker pull veracodedemolabs/verademo-java-github:latest

      - name: Run Docker image
        run: |
         docker run -p 8080:8080 veracodedemolabs/verademo-java-github:latest
         
 # Run DAST Scan against QA server
  Submit-DAST-Scan:
    runs-on: ubuntu-latest
    container: 
      image: veracode/api-signing:latest
    steps:     
      - name: Download Veracode-DAST-Config artifact
        uses: qiwi-forks/action-download-artifact@v2
        with: 
         github_token: ${{secrets.GITHUB_TOKEN}}
         workflow: 1-Checkout-Build-Artifact.yml
         name: Veracode-DAST-Config.json
        continue-on-error: true

      - name: List folder contents for visual
        run: |
         ls -la
         
      - name: Submit Veracode DAST Scan
        run: |
         http --auth-type=veracode_hmac POST "https://api.veracode.com/was/configservice/v1/analyses" < Veracode-DAST-Config.json
