# build the docker image and push it to the official veracode repo

name: push-veracode-docker-image

on:
  workflow_dispatch:
    
jobs:     
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v3
    
      - name: setup environment
        run: |
          VER=$(cat ./VERSION)
          echo "VERSION=$VER" >> $GITHUB_ENV

      - name: check-latest-version
        uses: addnab/docker-run-action@v3
        with:
          image: rancher/dind
          run: |
            docker manifest inspect kevinrise/vulnerable-verademo-java:${{ env.VERSION }} > /dev/null 2>&1
            exit_code=$?
            if [ $exit_code = 0 ]; then
              echo Image already exists, did you forget to bump the VERSION file?
              exit 1
            else 
              echo free to push new image
              exit 0
            fi

      - name: login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_VERA_USERNAME }}
          password: ${{ secrets.DOCKERHUB_VERA_PASSWORD }}

      - name: Build-Push Docker image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: |
            kevinrise/vulnerable-verademo-java:${{ env.VERSION }}
            kevinrise/vulnerable-verademo-java:latest
