# build the docker image and push it to the official veracode repo

name: push-veracode-docker-image

on:
  workflow_dispatch:
    
jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v3
    
      - name: setup environment
        run: |
          VER=$(cat ./VERSION)
          echo "VERSION=$VER" >> $GITHUB_ENV

      - name: login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_VERA_USERNAME }}
          password: ${{ secrets.DOCKERHUB_VERA_PASSWORD }}

      - name: Build-Push Docker image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: |
            kevinrise/vulnerable-verademo-java:${{ env.VERSION }}
            kevinrise/vulnerable-verademo-java:latest
