name: Veracode

on:
 # Enables manual runs
  workflow_dispatch:
  # Runs "Every at 5:04" (see https://crontab.guru)
  schedule:
  - cron: "4 5 * * *"

jobs:
  Veracode:
    runs-on: [ubuntu-latest]
    steps:

      - uses: actions/checkout@v2

      - name: Setup Veracode
        run: |
         curl -fsS https://tools.veracode.com/veracode-cli/install | sh

      - name: Package App
        run: |
         ./veracode package -s . -a

      - name: SAST Scan
        continue-on-error: true
        env:
         VERACODE_API_KEY_ID: ${{ secrets.VERACODE_API_KEY_ID }}
         VERACODE_API_KEY_SECRET: ${{ secrets.VERACODE_API_KEY_SECRET }}
        run: |
         ./veracode static scan ./verademo.war --summary-output sast-summary.txt

      - name: SCA Scan
        env:
         SRCCLR_API_TOKEN: ${{ secrets.SRCCLR_API_TOKEN }}
        run: |
         - curl -sSL https://download.sourceclear.com/ci.sh | sh
         
  # Upload security artifacts
      - name: Upload artifact with SCA app and container issues for this build
        uses: actions/upload-artifact@v3.1.1
        with:
           name: SCA-SAST-Issues-${{ github.run_id }}
           path: "*.json"
