name: Veracode

on:
 # Enables manual runs
  workflow_dispatch:
  # Runs "Every at 5:04" (see https://crontab.guru)
  schedule:
  - cron: "4 5 * * *"

jobs:
  Veracode:
    runs-on: [ubuntu-latest]
    steps:

      - uses: actions/checkout@v2

      - name: Setup Veracode
        run: |
         curl -fsS https://tools.veracode.com/veracode-cli/install | sh

      - name: Package App
        run: |
         ./veracode package -s ./ -a

      - name: SAST Scan
        run: |
         ./veracode static scan verademo.war
        env:
         VERACODE_API_KEY_ID: ${{ secrets.VERACODE_API_KEY_ID }}
         VERACODE_API_KEY_SECRET: ${{ secrets.VERACODE_API_KEY_ID_SECRET }}
